=== Orynik/LearnProject/College/C/XML_Project/schema.xsd
<?xml version = '1.0' encoding = 'utf-16'?>
<zs:schema xmlns:zs = 'http://www.w3.org/2001/XMLSchema'>
<zs:element name = 'teh'>
<zs:complexType>
<zs:sequence>
<zs:element name = 'stud' minOccurs = '0' maxOccurs = 'unbounded'>
<zs:complexType>
<zs:sequence>
<zs:element name = 'fam'></zs:element>
<zs:element name = 'name'></zs:element>
<zs:element name = 'group'></zs:element>
<zs:element name = 'rost'></zs:element>
</zs:sequence>
</zs:complexType>
</zs:element>
</zs:sequence></zs:complexType>
</zs:element></zs:schema>

=== Orynik/LearnProject/College/C/XML_Project/index.xml
<?xml version = '1.0' encoding = 'utf-16'?>
<?xml-stylesheet type = 'text/css' href = 'style.css'?>
<teh xmlns:xsi = 'http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation = 'schema.xsd'>
<stud>
<fam>
Ivanov</fam>
<name>
Ivan</name>
<group>
i-17-1</group>
<rost>
176</rost>
</stud>
<stud>
<fam>
Petrov</fam>
<name>
Vasya</name>
<group>
e-12-1</group>
<rost>
190</rost>
</stud>
<stud>
<fam>
Semenov</fam>
<name>
Petya</name>
<group>
e-15-1</group>
<rost>
160</rost>
</stud>
</teh>
